services:
  front-end:
    image: junaid777khan/group-chatly-frontend-optimized
    ports:
      - "3000:80"
    depends_on:
      - back-end
    build:
      context: ./front-end
      args:
        REACT_APP_SERVER_URL: http://localhost:5000
        REACT_APP_LOCALHOST_KEY: chat-app-current-user

  back-end:
    image: junaid777khan/group-chatly-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URL: mongodb+srv://jk387520:9PB3nCLCDqViLwBM@cluster0.sfnbfno.mongodb.net/chatly


